version: '3.8'

services:

  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres_db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  
  auth_service:
    build: auth-service
    environment: 
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/auth_db
    ports: 
      - "8080:8080"
    depends_on: 
      - postgres_db

  resource_service:
    build: resource-service
    ports: 
      - "8081:8081"
    depends_on: 
      - auth_service
  
    